### ISSUE TITLE
permit "resp" attribute in /teiCorpus/TEI/teiHeader/fileDesc/sourceDesc/bibl/relatedItem/bibl/date

### ISSUE THREAD

**Issue by kyarmey** [RILMMusicLit/tei_schema#1]

**Comment by northgardner** [comment]
"resp" is now permitted on <date> everywhere starting with version 1.0.9 of the schema. Journals is now using 1.0.9. Make sure everyone is using the /journals/tei_rilm.xsd version of the schema.
