### ISSUE TITLE
Add <place> to the schema

### ISSUE THREAD

**Issue by northgardner** [RILMMusicLit/tei_schema#11]
We need a way in MGG to encode variant place names alongside preferred place names and also to have them display properly. The best way to do this is to put the `place` element into our TEI schema, and mark up geographical headings like this:

```
<div type="heading">
<p><place><placeName>Preßburg</placeName>, slowak. <placeName type="alt">Bratislava</placeName>, ung. <placeName type="alt">Pozsony</placeName></p>
</div>
```

The CSS will have to be edited as well so that the rules for `placeName` in that location mirror the rules for `persName` in that location. Or in any event, so that it displays like the print articles.

**Comment by kyarmey** [comment]
I think so. I'll look into in the next couple of days.

**Comment by ahwitz** [comment]
(sorry to bug you, Jonathan)

**Comment by northgardner** [comment]
(Not a bother. A notification now and then from RILM is kind of fun! Hope you guys are making out OK in these tough times.)

**Comment by ahwitz** [comment]
Same to you!

**Comment by kyarmey** [comment]
This change is a bit involved. `<place>` is already in TEI, but it's not allowed in most of the contexts in which I imagine we'd use it. It might help if I have an example or 5 of its proposed use.

**Comment by ahwitz** [comment]
We've decided we're okay with `p > settlement/country/region > placeName` instead because those three work inline with text and are also semantically correct. Already documented in Fonto ticket.
